### ISSUE TITLE
Use of !$ in ruby 1.9

### ISSUE THREAD

**Issue by tribalvibes** [geokit/geokit#13]
GeoKit uses the pattern "message string" + !$
!$ is the exception object and is not implicitly convertible to a string (at least in ruby 1.9)
Thus the catenation fails and throws another exception. I replaced with, e.g. in GoogleGeocoder:

```
      logger.error "Caught an error during Google geocoding call: address: #{address.to_s} error: #{$!.inspect}"
```

adding .to_s explicit string conversion to the catenation would also work, but this shows both the error class and the message.

**Comment by lukasz-wojcik** [comment]
I have stumbled upon this `$!` in one of the forks (very old one) that the app which I maintaint use. This has already been rewritten in the gem

**Comment by ryankopf** [comment]
Only found one use of this, in geocoders.rb, and it appears to work. Open a new issue if you see more problems, thanks :)
