### ISSUE TITLE
Please add the possible configuration paramters

### ISSUE THREAD

**Issue by TheWudu** [geokit/geokit#131]
Hi!

Would be nice to have the possible configuration parameters documented, to not have to dive into the code and find somewhere that :kms and :nms are possible as unit. 

Regarding the documentation I expected :kilometers should be set.

Best regards,
TheWudu

**Comment by ryankopf** [comment]
This is documented in Readme.md presently, so this seems complete.

**Comment by TheWudu** [comment]
Yes it's there now.
