### ISSUE TITLE
GoogleGeocoder result sorting is wrong

### ISSUE THREAD

**Issue by bcneal** [geokit/geokit#155]
The GoogleGeocoder parse_json method returns equal-accuracy results in the opposite order that Google returns them due to an overly-simplistic accuracy sort.  For example, when I give the input "new york new york", google returns results for "New York City, New York" and "New York, Missouri" in that order, but both have the location_type set to "APPROXIMATE".  GoogleGeocoder maps this location_type to ACCURACY=4 and then does a reverse-sort on accuracy, which has the side effect of inverting the order from what the Google API returned.

I've monkeypatched GoogleGeocoder to group the results by accuracy, sort the list of groups, then flatten them back out into a single array and the results make a lot more sense.

**Comment by adailey14** [comment]
I'm sorry I never got around to putting the patch into a pull request, but the behavior appears to be fixed in the latest release version. So @bcneal you may want to close this issue.

**Comment by mnoack** [comment]
Closing as @adailey14 says it appears to be resolved.
