### ISSUE TITLE
distance_to results using different units are incorrect!  :meters is not defined ? 

### ISSUE THREAD

**Issue by tilo** [geokit/geokit#157]
Two bugs:

1) when distance_to is presented with an invalid unit, it does not raise an exception!!
    This is really bad, because it will silently just return the value for the default unit,
     and you'll just get incorrect results (and maybe never know)

 2) :meters is mentioned as a unit in your README file, but when I specify it,
      I don't get any different result -- e.g. the above bug masks the missing unit, and 
      returns the result in :miles instead 

```
prev_point = ::Geokit::LatLng.new( -33.86793 , 151.19439 )
this_point = ::Geokit::LatLng.new( -33.86891 , 151.19496 )

dist = prev_point.distance_to(this_point, :units => :miles)
=> 0.07527845689074655

> dist = prev_point.distance_to(this_point, :units => :utter_nonsense)
=> 0.07527845689074655    # OUTCH!!! THIS SHOULD RAISE AN EXCEPTION!!

> dist = prev_point.distance_to(this_point, :units => :meters)
=> 0.07527845689074655    # THIS IS IN MILES -- SILENTLY FAILING INSTEAD OF RAISING AN EXCEPTION!!  :meters are not implemented??

> dist = prev_point.distance_to(this_point, :units => :kms)
=> 0.1211230371372112   # this works

```

**Comment by mnoack** [comment]
Thanks for reporting the issue. Is it possible you could write a test and make a PR to fix the bug.

Your code above is basically a test. See test folder in project for examples, there should be some that say 'raise' to test exceptions.

Then once you have a test you should be able to search for 'distance_to' and see where that's calling and make the appropriate code change to raise an exception if units are not specified.

**Comment by mnoack** [comment]
PS. I'm happy to offer further advice in making the PR/test, just ask me questions.

**Comment by kikihakiem** [comment]
@tilo I've made a PR (https://github.com/geokit/geokit/pull/158) to raise exception when units supplied is invalid or not supported. `:meters` unit works as expected however.

**Comment by mnoack** [comment]
Closing as https://github.com/geokit/geokit/pull/158 is merged
