### ISSUE TITLE
Please change the http to https in the yandex geocoder url

### ISSUE THREAD

**Issue by nazarok** [geokit/geokit#169]
in file: lib/geokit/geocoders/yandex.rb
in the def self.submit_url

replace http://geocode-maps.yandex.ru to https://geocode-maps.yandex.ru

because http does not work for yandex

**Comment by mnoack** [comment]
Is it possible for you to do a PR for this change?
Do you know if there's any documentation from yandex that HTTP no longer works?

Also, do you know if there's a free test yandex.ru account (or can you get one) so geokit can ensure it picks up on these things and can test changes in future (currently the original author has fixtures assuming yandex won't change, which is often the only solution)

**Comment by nazarok** [comment]
> Is it possible for you to do a PR for this change?

[Pull request](https://github.com/geokit/geokit/pull/170)

> Do you know if there's any documentation from yandex that HTTP no longer works?

On their page:
`https://tech.yandex.com/maps/doc/geocoder/desc/concepts/input_params-docpage/`
specified protocol http, but their example:
`http://geocode-maps.yandex.ru/1.x/?geocode=Kabasakal+Caddesi,+Istanbul,+Turkey&lang=en-US`
 redirect to:
`https://geocode-maps.yandex.ru/1.x/?geocode=Kabasakal+Caddesi,+Istanbul,+Turkey&lang=en-US`

> Also, do you know if there's a free test yandex.ru account (or can you get one) so geokit can ensure it picks up on these things and can test changes in future (currently the original author has fixtures assuming yandex won't change, which is often the only solution)

can't say anything about this

**Comment by mnoack** [comment]
Closes as your PR https://github.com/geokit/geokit/pull/170 is merged. Thanks again @nazarok I really appreciate you finding those links and examples so we have a reference as to why it has changed.
