### ISSUE TITLE
Mapbox (Carmen GeoJSON format) is parsed incorrectly

### ISSUE THREAD

**Issue by scudco** [geokit/geokit#173]
Currently the Mapbox implementation sets address attributes based on the `features[].context`, but that object only contains _parent_ information about a `feature` according to the [Carmen GeoJSON](https://github.com/mapbox/carmen/blob/master/carmen-geojson.md) format.

```
1.9.3-p448 :031 > foo = Geokit::Geocoders::MapboxGeocoder.geocode('Los Angeles, CA, United States')
 => Provider: mapbox
Street:
City:
State: California
Zip:
Latitude: 34.0522
Longitude: -118.2437
Country:
Success: true
1.9.3-p448 :032 > foo.city
 => nil
```

I am looking into how to best parse the Carmen GeoJSON format now.

**Comment by mnoack** [comment]
@scudco do you think you could look at my changes to google geocoder in https://github.com/geokit/geokit/pull/197/files and apply the same principles to the mapbox geocoder and make a pull request for this, then I will happily merge it in and get a release out.
