### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by evenwestvang** [geokit/geokit#18]
Inflector::url_escape doesn't handle escaping of UTF-8. Replacing it with vanilla CGI.escape works for me.

Likewise the result of do_geocode also needs to have its encoding forced to UTF_8 before being passed on to rexml.

**Comment by ryankopf** [comment]
It appears url_escape already is just a wrapper around vanilla CGI.escape.

Closing issue as it's been so long. If you see this as still being an issue, please open a new issue or submit a PR. Thank you.
