### ISSUE TITLE
Running the tests

### ISSUE THREAD

**Issue by smingins** [geokit/geokit#182]
Just wondering if there is a trick to running the test suite?

I'm looking to fix/support setting state value for mapbox when geocoding a state value.

The tests for the mapbox geocoder fail and it seems like it's not picking up any of the VCR cassettes

Here is a gist of the output for that test https://gist.github.com/smingins/9f6cefeb4e75dbef29bf9ad26912e132

I'm using Ruby 2.3.0

**Comment by mnoack** [comment]
Are you running the code off the master branch with no modifications?
That works fine for me with the command you ran (bundle exec rake test TEST=test/test_mapbox_geocoder.rb)

Travis (travis-ci.org) seems to be able to run it fine also.

I tried it on ruby 2.3.0 as well. Could you include the git sha of the commit your running and git status to ensure we're running the same code? (maybe a fresh clone into a new directory is a good idea too)

**Comment by smingins** [comment]
I tried a fresh clone.  The only modification is the .ruby-version file.

```
smingins:~/Projects/Temp/geokit[master] $ git st
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.ruby-version

nothing added to commit but untracked files present (use "git add" to track)
```

````
smingins:~/Projects/Temp/geokit[master] $ git show-ref master
23f71f9f89915c21b860f3d45079e412a5eecc7a refs/heads/master
23f71f9f89915c21b860f3d45079e412a5eecc7a refs/remotes/origin/master
smingins:~/Projects/Temp/geokit[master] $ git last
commit 23f71f9f89915c21b860f3d45079e412a5eecc7a
Author: Michael Noack <michael@noack.com.au>
Date:   Sat Apr 30 00:04:49 2016 +0930

    Extract URLs to shorten lines/remove duplication
smingins:~/Projects/Temp/geokit[master] $ 
````

Still same results.  When digging yesterday it felt like something odd with VCR was happening for me.  I added a new test with a VCR block that I thought would have created a cassette on it's initial run, but did not.

Not sure if that sparks any thoughts as to what might be happening for me locally?

Otherwise I'll keep digging :-)

Cheers
Shane

**Comment by mnoack** [comment]
@smingins I can ONLY get the same error as your initial gist if I delete the cassettes
e.g. I did this to replicate your error:
rm fixtures/vcr_cassettes/mapbox_*

Can you confirm that these mapbox cassettes exist and are not empty AND they match those in the geokit repo in master?

Interestingly there should be no difference but clearly geokit is now out of date compared to the live mapbox system by the looks of it.

But of course there still is some issue with your setup and it not using the provided cassette.

**Comment by smingins** [comment]
@mnoack looks like I am hitting a bug in vcr's webmock handler.  I created a small project and used vcr's example setup using Net:HTTP to get http://www.iana.org and it was not hitting any of the after request handlers to record and write the interaction.  I switched it to use Faraday and it works as expected.  I have a rails project that works as expected with webmock so I am puzzled.

Thanks for the help though ... hopefully I can get this resolved and get a PR in for the mapbox tweak :-)

**Comment by smingins** [comment]
@mnoack so an update ... for the tests to pass for me I needed to add:

````require 'webmock/test_unit'```` to ````helper.rb````

I don't know why but that fixed all cases.  And when using minitest it was ````require 'webmock/minitest'```` and likewise for rspec (which was why the existing rails project I had was working)

So not sure why I hit that and others don't.

**Comment by mnoack** [comment]
@smingins Thanks a bunch, this started driving me nuts as well as it started affecting me. Turns out webmock 2.0 was just released recently which requires this addition (https://github.com/bblimke/webmock/blob/master/CHANGELOG.md#200)

So a week ago it was fine, but a fresh bundle now fails. Downgrading to webmock 1.x fixes it (or better the solution you gave)

I'll make a fix referencing the changelog for webmock very soon
