### ISSUE TITLE
polygon.cointains?(point) not working properly in Heroku

### ISSUE THREAD

**Issue by pinzonjulian** [geokit/geokit#208]
Hi! I'm having trouble getting the `contains?(point)`method to work on Heroku.

My setup is as follows:

- Rails 5.0.1
- `gem 'geokit-rails'` (but i'm using geokit stuff exclusively)
- ruby 2.3.3

Dependencies in the gemfile lock are:

- geokit (1.11.0)
- geokit-rails (2.3.0)
  - geokit (~> 1.5)
  - rails (>= 3.0)

I have an address model with `latitude: float, longitude: float` and the following method:
```ruby
def is_within_city_limits?
    boundaries = city.boundaries.select(:id, :latitude, :longitude)
    polygon = Geokit::Polygon.new( boundaries.map{ |b| Geokit::LatLng.new(b.latitude, b.longitude) }.flatten )
    point = Geokit::LatLng.new(latitude, longitude)

    polygon.contains?(point)
end
```
An address has_one city and a city has_many boundaries. Boundaries also have `latitude: float, longitude: float` and where added manually to the DB.

In my local environment things work just as expected. However in production environment, they don't. Addresses that are actually within city limits return `false`.

Any clues? Thanks in advance!

**Comment by wizzor** [comment]
Hi,
I am having the same issue, in fact the issue also presents itself with the bounds object, as follows:

```

np = Geokit::LatLng.new(60.193625, 24.279660)
sp = Geokit::LatLng.new(59.959380, 24.943419)
Geokit::Bounds.new(np, sp)
bounds.contains? bounds.center # false

```

Obviously the center of a bounds object should fall within the bounds.

From Gemfile.lock

```

geokit (1.11.0)
geokit-rails (2.3.0)
rails (= 5.1.3)
mysql2 (~> 0.3.18)

```

**Comment by pinzonjulian** [comment]
Hi Wizzor!

I found the problem in my case was due to the polygon points order. When querying from the database, I was using a `select` clause which modified the order of the coordinates. Once I ordered them correctly, everything worked as expected.

In my case, it seems I was really lucky when testing in my development environment and all cases seemed to work correctly. When testing in production with massive amounts of data, I wasn't lucky anymore.

**Comment by wizzor** [comment]
The documentation simply suggests passing in an array of Geokit::LatLng objects, is there a specific order in which you are passing them in?

**Comment by pinzonjulian** [comment]
Yes.

Imagine you are creating a polygon in vector illustration software like Illustrator or Sketch using the pen tool. Each time you click, a point is drawn in the canvas and it will connect to the next point. If you want to create a square you would place points like:

1. top-left
2. top-right
3. bottom-right
4. bottom-left

If you were to to something like:
1. top-left
2. bottom-rigth
3. top-right
4. bottom-left

You would end up with the same 4 points but the drawing would be like a bow tie.

Also, your first point should be equal to your last point so the shape closes. If you don't do that, geokit will do it for you.
