### ISSUE TITLE
Use https for nominatim.openstreetmap.org

### ISSUE THREAD

**Issue by grischard** [geokit/geokit#213]
The nominatim geocoding service at nominatim.openstreetmap.org is available over https, and [will soon start redirecting all http requests to https](https://lists.openstreetmap.org/pipermail/geocoding/2018-January/001918.html).

Some ruby http libraries don't follow redirects by default.

Would it please be possible to make all nominatim requests over https?

**Comment by dfabreguette-ap** [comment]
The days has come ! Nominatim / OSM now redirects to https.
I just installed the gem and get no results with OSM Geocoder as the url is hard-coded with http and the 301 redirection is not followed ...
I pushed a pull request to set https protocol as hard-coded, but it might be usefull to use a gem like "RestClient" that could follow 301 redirect....

**Comment by mnoack** [comment]
Thanks @dfabreguette-ap - That PR has been merged and a gem has been released. Good news @grischard 

Whilst I'm rarely addressing reporting issues on this repo, I'm reasonably responsive on merging PRs that people have done.

**Comment by dfabreguette-ap** [comment]
Great thanks :)
