### ISSUE TITLE
CaGeocoder error when passing a Geokit::GeoLoc object as address

### ISSUE THREAD

**Issue by siannopollo** [geokit/geokit#224]
It appears the code used to handle this but the change [implemented in this commit](https://github.com/geokit/geokit/commit/d484c627f2b49ddae9cee73bd27a97d3329774dc#diff-2d95c465d3d745d18894ecfec3dfd6dd) removed the ability to pass in a GeoLoc object and results in the error:
```
undefined method `encoding' for #<Geokit::GeoLoc>
```

The fix should be pretty simple, and is implemented in other geocoders, which is to get an address string from whatever is passed in to the method:
```
address_str = address.is_a?(GeoLoc) ? address.to_geocodeable_s : address
```
I don't know if I will have time to make the change and an associated test and pull request, so if someone else wants to jump on this, feel free.

**Comment by mnoack** [comment]
Closing as the PR you did to fix this is now merged. Thanks again.
