### ISSUE TITLE
Heading bug

### ISSUE THREAD

**Issue by ben-fly2success** [geokit/geokit#230]
I have some issues on the endpoint and heading methods that seems to send incorrect results.

For exemple the heading between 2 points are not exactly -180 degrees if you go from point A to point B and point B to point A : 
``` ruby
p1 = Geokit::LatLng.new(48.571182027451826, -0.4402671592964547)
p2 = Geokit::LatLng.new(48.525939287181586, -0.3230002328606039)

p1.heading_from(p2)                                             
=> 300.2778935811772

p2.heading_from(p1)             
=> 120.19000000000386
```

**Comment by ryankopf** [comment]
This is probably a floating point number rounding error. I wouldn't expect super precise results.
