### ISSUE TITLE
Incorrect Geokit::GeoLoc#hash method prevents serialization

### ISSUE THREAD

**Issue by tadman** [geokit/geokit#5]
Because GeoKit::GeoLoc has a hash method that returns a hash instead of the expected Fixnum, it is not always possible to serialize these objects. (See: http://apidock.com/ruby/Object/hash)

It would be preferable if the methods that return hashes are called to_h, or to_hash, or perhaps both, as is convention.

This is easily demonstrated as:

```
GeoKit::Geocoders::MultiGeocoder.geocode('123 main st.').all.to_yaml
# => TypeError: can't convert Hash into Integer
```

**Comment by ryankopf** [comment]
Closing issue as it's been so long. If you see this as still being an issue, please open a new issue or submit a PR. Thank you.
