### ISSUE TITLE
TypeError using GeoLoc object

### ISSUE THREAD

**Issue by blythedunham** [geokit/geokit#64]
Using ruby 1.9.3 I see TypeError when passing a GeoLoc object to 

``` ruby
1.9.3-p0 :003 > geoloc = GeoKit::GeoLoc.new( city:'asdfasdf----', street:'4444', state: 'Germany')
1.9.3-p0 :003 > results = Geokit::Geocoders::GoogleGeocoder.geocode( geoloc )
TypeError: can't convert TypeError into String
    from/.rvm/gems/ruby-1.9.3-p0@rails32/gems/geokit-1.6.5/lib/geokit/geocoders.rb:508:in `+'
    from/.rvm/gems/ruby-1.9.3-p0@rails32/gems/geokit-1.6.5/lib/geokit/geocoders.rb:508:in `rescue in xml2GeoLoc'
    from/.rvm/gems/ruby-1.9.3-p0@rails32/gems/geokit-1.6.5/lib/geokit/geocoders.rb:479:in `xml2GeoLoc'
    from/.rvm/gems/ruby-1.9.3-p0@rails32/gems/geokit-1.6.5/lib/geokit/geocoders.rb:465:in `do_geocode'
    from/.rvm/gems/ruby-1.9.3-p0@rails32/gems/geokit-1.6.5/lib/geokit/geocoders.rb:129:in `geocode'
```

Fix is easy: call `$!.to_s` on all instances

Related is `"Some String" +address`
makes : Caught an error during Google geocoding call: can't convert Geokit::GeoLoc into String
when passing a GeoLoc object instead of a string
again `address.to_s` does the trick

**Comment by ryankopf** [comment]
Closing issue as it's been so long and there have been many changes in the code since this comment. If you see this as still being an issue, or experience any other bugs, please open a new issue or submit a PR. Thank you.
