### ISSUE TITLE
GeoIp Provider

### ISSUE THREAD

**Issue by jsuchal** [geokit/geokit#8]
Hi!

Any change to merge this provider into master? 

http://github.com/DefV/geokit-geoip-provider

Thanks!

**Comment by ryankopf** [comment]
Any merge requests should be submitted as a Pull Request and you should create a test_mygeocodername.rb unit test file as well.

Closing issue as it's been so long. If you see this as still being an issue, please open a new issue or submit a PR. Thank you.
